### ISSUE TITLE
Saving checkpoints in continued training

### ISSUE THREAD

**Issue by d-ataman** [joeynmt/joeynmt#128]
Hi there,

I have tried loading a previous checkpoint and continuing my training but when I do this the training goes on without saving the checkpoints. It does the validation at every specified step but never saves the model in the directory. Is there a specific command in the config I should specify about continued training? 
Thanks so much!

**Comment by juliakreutzer** [comment]
Hey @d-ataman,
It's probably because the model is not improving over the previous metric. Joeynmt only stores checkpoints when the previous best value is passed. The metric for defining what "best" is is set here: https://github.com/joeynmt/joeynmt/blob/master/configs/small.yaml#L59. You can also choose to reset this tracking and write new checkpoints if you specify it with this variable:  https://github.com/joeynmt/joeynmt/blob/master/configs/small.yaml#L33.
