### ISSUE TITLE
validation process takes too long time

### ISSUE THREAD

**Issue by kimziwoo** [joeynmt/joeynmt#165]
Hi. 
I am training transformer model with 800K training data, 100K validation data. 
But it takes too long time in validation process, almost 2days for just evalutating once.  
I set my validation frequency 2000, and validation batch 4096, using 3 gpus.
training batch is set to 4096. 
Do you have any idea to shorten validation time?

**Comment by juliakreutzer** [comment]
Hi @kimziwoo,
thank you for your question! I can see the following options:
1. Decreasing the _validation frequency_ will help to run it less frequently, but it does not solve the problem of the duration of a single evaluation run and training waiting for it. 
2. _Subsampling_ <5k sentences of those 100k (it's a lot! most MT models are validated only on a few thousand sentences, commonly 2-3k), otherwise you're going to spend too much time on translation. 
3. Not currently implemented in JoeyNMT: You could start a _separate validation process_ running on a different machine than training. Checkpoints are written in regular intervals by the training process, and the validation process just picks up the most recent one and runs validation. So if you have multiple GPUs available, you could reserve one of them for validation only. However, even with asynchronous validation, you'd still have to wait those 2 days for one validation run, which takes probably longer than training the model on 800k for many epochs.

So my recommendation is definetely (2). If you absolutely need all 100k sentences for validation, you probably need to implement something like (3). 
Hope that helps!

**Comment by kimziwoo** [comment]
Thanks for answering! 
I will try (2) and (3). Thanks!
