### ISSUE TITLE
Joeynmt and Nvidia-100

### ISSUE THREAD

**Issue by jbyunes** [joeynmt/joeynmt#166]
Hi, I've been unable to set correctly my Linux environment to get joeynmt properly working with my NVIDIA A100 GPU. I tested several python/CUDA/Driver settings but got stuck at some point each time.
Is there anybody here that can't give me details about it?
Best.

**Comment by may-** [comment]
Hi @jbyunes,

sorry for the late reply.
I'm also using Nvidia A100, and joeynmt works as expected on it. Could you please describe the error in details?

My environment:
- GPU: Nvidia A100
- CUDA v11.5
- torch 1.11.0
- python 3.9

**Comment by jbyunes** [comment]
I broke my old environment but now when I launch joeynmt it says "ModuleNotFoundError: No module named 'torchtext.legacy'". I have cuda11.6 torch 1.11.0 python3.9

**Comment by may-** [comment]
Ah, this is a known problem. We are working on removing torchtext dependencies. The new version without torchtext will become available soon. (sorry, I cannot promise a release date, though.)

Since it's not related to Nvidia A100, I'll close this issue. Could you please subscribe #158, instead? We'll inform there, when we merge the new version w/o torchtext into main repo. Sorry for the inconvenience and thanks for your patience!
