### ISSUE TITLE
Stopping and resuming training

### ISSUE THREAD

**Issue by tarekzaki115** [joeynmt/joeynmt#172]
Can I stop my model from training and resume it later on another machine use checkpoints while maintaining the number of epochs?
and if that is possible can I resume training on colab using the checkpoint?

**Comment by juliakreutzer** [comment]
Hi @tarekzaki115,
yes you can resume on any machine, as long as you copy over checkpoint and vocabulary files and adjust the config to read these files in and to write into a new model directory on your new machine. See https://joeynmt.readthedocs.io/en/latest/faq.html "What if training is interrupted and I need to resume it?".
However, the epoch count will be reset (because we technically can't know if you're continuing to train on the same data or different data), but the step count continues.
