### ISSUE TITLE
Training with Transformer with BPE error

### ISSUE THREAD

**Issue by AfriLANG4** [joeynmt/joeynmt#68]
I am training isiXhosa > English NMT for a small (XhosaNavy Corpus)<45k. 
Tested JoeyNMT with Luong and Badhanau with no errors, but ...

The produced:
1. Got errors when **training** the transformer_BPE approach for isiXhosa > English
2. configuration file: 
name: "xhen_transformer"
data:
    src: "xh"
    trg: "en"
    train: "test/data/navy_xhen/train-bpe"
    dev: "test/data/navy_xhen/dev-bpe"
    test: "test/data/navy_xhen/test-bpe"
    level: "bpe"
    lowercase: True
    max_sent_length: 50
    src_vocab: "test/data/navy_xhen/vocab-bpe.xh"
    trg_vocab: "test/data/navy_xhen/vocab-bpe.en"
    ....
3. code call [!python -m joeynmt train configs/xhen_transformer_bpe.yaml]

**Logged output**
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/joeynmt/joeynmt/__main__.py", line 41, in <module>
    main()
  File "/content/joeynmt/joeynmt/__main__.py", line 29, in main
    train(cfg_file=args.config_path)
  File "/content/joeynmt/joeynmt/training.py", line 535, in train
    model = build_model(cfg["model"], src_vocab=src_vocab, trg_vocab=trg_vocab)
  File "/content/joeynmt/joeynmt/model.py", line 226, in build_model
    "Embedding cannot be tied since vocabularies differ.")
joeynmt.helpers.ConfigurationError: Embedding cannot be tied since vocabularies differ.

**Expected behavior**
output : Hello! This is Joey-NMT.
params: ...
config

**System (please complete the following information):**
 - OS: Google Colab VM runtime
 - GPU 
 - Python >=3.0

**Additional context**
I am a novice and just stated with NMT projects and JoeyNMT toolkit is a good start

**Comment by juliakreutzer** [comment]
Hi @AfriLANG4!

Cool project! :sunglasses: And thanks for the detailed description of your issue!

The problem here is the line `tied_embeddings: True` in the configurations. Tied embeddings mean that you use the same embedding matrices for source and target, and that only works if you have a joint vocabulary, i.e. if `src_vocab` equals `trg_vocab`. This is usually used to save parameters and when vocabularies are relatively similar (e.g. English and French).

In order to fix it you can do the following:

1. Set `tied_embeddings: False` to disable embedding tying.
2. Work with a joint BPE model, by learning BPEs on the concatenation of source and target. This will result in a joint vocabulary.

**Comment by AfriLANG4** [comment]
Thanks, it works fine.

**Comment by atikaakmal** [comment]
Hi @juliakreutzer,

I am using the joint Bbpe vocabulary that is created by this command  (ubword-nmt learn-joint-bpe-and-vocab --input {train_file}.L1 {train_file}.L2 -s {num_operations} -o {codes_file} --write-vocabulary {vocab_file}.L1 {vocab_file}.L2). 
After getting the **sr_vocab.de and trg_vocab.en** files, I am using this same vocab files in my config file. As I am using joint vocab, that's why I keep the **(tied_embedding= true)** in config file.

**The size of src_vocab and trg_vocab is not equal (I dont think so the size should be equal).**

But I dont know why I am getting this error 

**File "C:\Users\atak01\Desktop\recheck\joeynmt\joeynmt\model.py", line 227, in build_model
    "Embedding cannot be tied since vocabularies differ.")
joeynmt.helpers.ConfigurationError: Embedding cannot be tied since vocabularies differ.**


**config file:** 
data:
    src: "de"
    trg: "en"
    train: "data/train-data/train.tok.bpe"
    dev: "data/dev-data/wmt15-de-en.tok.bpe"
    test: "data/test-data/wmt17-de-en.tok.bpe"
    level: "bpe"
    lowercase: Flase
    max_sent_length: 100
    src_vocab: "data/vocab/vocab.de-en.de"
    trg_vocab: "data/vocab/vocab.de-en.en"
    tied_embeddings: True
    tied_softmax: True

**Error:**
Traceback (most recent call last):
  File "C:\Users\atak01\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\atak01\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\atak01\Desktop\recheck\joeynmt\joeynmt\__main__.py", line 41, in <module>
    main()
  File "C:\Users\atak01\Desktop\recheck\joeynmt\joeynmt\__main__.py", line 29, in main
    train(cfg_file=args.config_path)
  File "C:\Users\atak01\Desktop\recheck\joeynmt\joeynmt\training.py", line 632, in train
    model = build_model(cfg["model"], src_vocab=src_vocab, trg_vocab=trg_vocab)
  File "C:\Users\atak01\Desktop\recheck\joeynmt\joeynmt\model.py", line 227, in build_model
    "Embedding cannot be tied since vocabularies differ.")
**joeynmt.helpers.ConfigurationError: Embedding cannot be tied since vocabularies differ.**

Thanks

**Comment by may-** [comment]
How about constructing the joint vocab using [scripts/build_vocab.py](https://github.com/joeynmt/joeynmt/blob/master/scripts/build_vocab.py)?

**Comment by atikaakmal** [comment]
Hi @may- 

measn that after getting the src and trg vocab file that I am geeting by apply this command ((subword-nmt learn-joint-bpe-and-vocab --input {train_file}.L1 {train_file}.L2 -s {num_operations} -o {codes_file} --write-vocabulary **{vocab_file}.L1 {vocab_file}.L2)**.), then run the build_vocab script on that files?

If yes how we can run this build_vocab.py script (means how we will give file names etc).

Could you please tell why  am getting this error that **joeynmt.helpers.ConfigurationError: Embedding cannot be tied since vocabularies differ.**

**Comment by may-** [comment]
actually, you don't need to get vocab files from subword-nmt. The build_vocab.py script takes pre-tokenized train files as input and returns a joint vocab file.  
- call the script:
  ```
  $ python path/to/scripts/build_vocab.py train.bpe.en train.bpe.de --output_path joint_vocab.txt
  ```
- then specify the same file for both sides in config:
  ```
  src_vocab: "joint_vocab.txt"
  trg_vocab: "joint_vocab.txt"
  ```

### a bit of background:

First of all, joeynmt doesn't expect subword-nmt's vocab file format.  
joeynmt expects the vocab file with the format: one token per line. For en-de joint vocab, something like this:
```
,
.
s
the
and
in
und
to
die
of
a
[...]
```
joeynmt checks if the vocab dictionaries are equivalent in case `tied_embeddings == True`:
https://github.com/joeynmt/joeynmt/blob/75806e087d139f83e1b19e60a89eb71ade8b7e3f/joeynmt/model.py#L221 That is, you need to specify the same vocab file for both sides in config. Otherwise you'll get the Configuration error.


On the other hand, subword-nmt exports the vocab list per input file, even in case of joint vocab training. Looking at https://github.com/rsennrich/subword-nmt/blob/master/subword_nmt/learn_joint_bpe_and_vocab.py, they internally built a combined vocab (line 94), but export a list per language (line 122), so something like this:
- subword-nmt_vocab.en (built from `train.en` file)
```
, 185020
. 159679
the 130988
and 93420
to 76247
of 71671
a 66286
[...]
```
- subword-nmt_vocab.de (built from `train.de` file)
```
, 227911
. 164655
und 82988
die 75457
sie 50410
das 48412
der 48051
[...]
```
first column: token surface, second column: frequency in the given file.  
And because they count the frequency per file, the size of vocab file is different.
```
$ wc -l subword-nmt_vocab.*
 30697 subword-nmt_vocab.de
 21593 subword-nmt_vocab.en
 52290 total
```

If you want to use subword-nmt's vocab files instead of the output from build_vocab.py, then you could convert them to the joeynmt vocab format as follows:
```
$ cat subword-nmt_vocab.* | sort -r -n -k 2 | cut -f1 -d$' ' | uniq > joint_vocab.txt
```
I haven't tested, if it really works, though. I personally recommend to use `build_vocab.py`. I hope this comment helps!

**Comment by atikaakmal** [comment]
Hi @may- 

Thank you so much. This solution is worked for me and again I am highly thankful to you. Because I was strugling a lot from 2 weeks and you solution solve my problem. 

God bless you.

**Comment by atikaakmal** [comment]
Hi @may- 

Could you please also advice me, how we can **turncate rawdatasets** **if dataset is not parallel** i.e. I have europal-v7.de (**total number of line 13500**) and europal-v7.en datasets (**total number of line 13000**). The first 13000 lines are parallel but europal-v7.de has 500 extra lines that has **not parallel** english translation. Is it that fine If i will turncate manually or should use library or script to turncate the data. Or joeynmt has some script?

Also, how we can merge different raw datasets for example I have two different raw datasets **europal-v6.(de and en)** and **newscommentar.(de and en)** and I want to **make one file** (train.de and train.en). Is it any specific script and library to merge these files.

I would be highly thankful to you.

**Comment by joeynmt** [comment]
Thanks @may- for your help and excellent explanation!

@atikaakmal I'm surprised your Europarl data is not parallel. It is supposed to be... Where did you download it from? https://www.statmt.org/europarl/ lists 1,920,209 sentences for en-de, and I can confirm that the archive for download there contains them.

Most convenient for simple file manipulation like concatenation are probably bash tools/scripts, if you are a bash user. For example with `cat dataset1 dataset2 > dataset1and2` you can concatenate two files and paste the output into ´dataset1and2´.

**Comment by atikaakmal** [comment]
Hi @joeynmt 

Thanks for you comment. The problem is resolved now.

**Comment by Nibedita-Roy** [comment]
Hi @joeynmt ,
 Could You give some solution of the give error
"ImportError: cannot import name 'BOS_ID' from 'joeynmt.constants' (/usr/local/lib/python3.7/dist-packages/joeynmt/constants.py)"
My source and destination languages are  Assamese to Bengali

**Comment by may-** [comment]
Hi @Nibedita-Roy ,

`BOS_ID` was introduced in joeynmt v2.
I guess there is a version mismatch. Have you updated the joey  recently but keep using an old model, maybe?
Please check the version number.

We need a bit more context to reproduce your error. Which command did you use, when you've seen that error message above?
