### ISSUE TITLE
<pad> exists in prediction file

### ISSUE THREAD

**Issue by yukiyakiZ** [joeynmt/joeynmt#95]
**Describe the bug**
After training, when I used the model to generate the hypothesis on dev and test set, there are <pad> at the end of some generated sentences.

**Logged output**
One example of the output is:
but/and horses then- redup- tell s.o. - \<pad\> \<pad\>\<pad\>\<pad\>\<pad\>\<pad\>\<pad\>\<pad\>\<pad\>\<pad\>\<pad\>\<pad\>\<pad\>\<pad\>

**System (please complete the following information):**
 - MAC OS
 - GPU
 - Python Version 3.7.4

**Comment by juliakreutzer** [comment]
Hi @yukiyakiZ 
this is a common phenomenon if the model is not well trained, usually in the beginning of training.
During inference, it should generate an EOS token, after which the padding symbols usually follow. Everything that is generated after EOS is cut off for the final translation, so that usually covers the padding as well. But if your model for some reason does not generate EOS, then the padding will be visible. You might want to doublecheck your data processing and that EOS is generated. 
The [function for turning indices back into words](https://github.com/joeynmt/joeynmt/blob/master/joeynmt/vocabulary.py#L125) now also contains a flag to skip any padding. By default it is turned on, so if you run the code again, the paddings should disappear.

**Comment by yukiyakiZ** [comment]
Thank you so much! It has been fixed and the paddings disappeared.
Best
